<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="wkssuresh" name="com.econsys.testCases.NewLink" tests="6" failures="1" timestamp="22 Feb 2017 07:08:00 GMT" time="15.780" errors="0">
  <testcase name="newLinkSavedRTQ" time="15.764" classname="com.econsys.testCases.NewLink">
    <failure type="java.lang.AssertionError" message="expected [&quot;New link saved rtq&quot;] but found []">
      <![CDATA[java.lang.AssertionError: expected ["New link saved rtq"] but found []
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.econsys.Genriclibrery.CommonUtils.assert_Test(CommonUtils.java:204)
	at com.econsys.testCases.NewLink.newLinkSavedRTQ(NewLink.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </failure>
  </testcase> <!-- newLinkSavedRTQ -->
  <testcase name="newLinkStatuOfResubmitQuote" time="0.000" classname="com.econsys.testCases.NewLink"/>
  <testcase name="newLinkStatuOfSubmitQuote" time="0.000" classname="com.econsys.testCases.NewLink"/>
  <testcase name="newLinkSubmitQuote" time="0.001" classname="com.econsys.testCases.NewLink"/>
  <testcase name="newLinkAssignSalesLeader" time="0.015" classname="com.econsys.testCases.NewLink"/>
  <testcase name="newLinkPrepareQuote" time="0.000" classname="com.econsys.testCases.NewLink"/>
</testsuite> <!-- com.econsys.testCases.NewLink -->
