<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="wkssuresh" name="com.econsys.Projects.Save_Cancel_Reject_DonotProceed" tests="1" failures="0" timestamp="20 Sep 2016 12:29:05 GMT" time="18.805" errors="1">
  <testcase name="rejectDonotPro_CP6_to_CP9" time="18.805" classname="com.econsys.Projects.Save_Cancel_Reject_DonotProceed">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.econsys.Projects.Deliveryreview_ProjectCompleted.procomplete(Deliveryreview_ProjectCompleted.java:46)
	at com.econsys.Projects.Save_Cancel_Reject_DonotProceed.saveCancelReject_CP7(Save_Cancel_Reject_DonotProceed.java:400)
	at com.econsys.Projects.Save_Cancel_Reject_DonotProceed.rejectDonotPro_CP6_to_CP9(Save_Cancel_Reject_DonotProceed.java:392)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </error>
  </testcase> <!-- rejectDonotPro_CP6_to_CP9 -->
</testsuite> <!-- com.econsys.Projects.Save_Cancel_Reject_DonotProceed -->
